---
- name: Execute PowerShell Script on Windows Securely
  hosts: windows
  gather_facts: no

  tasks:
    #- name: Ensure Temp and UPTIME Directories Exist
     # win_file:
      #  path: C:\temp\UPTIME
       # state: directory

    - name: Execute PowerShell Script with Credentials
      win_shell: |
        $User = "{{ ansible_user }}"
        $Pass = "{{ ansible_password }}"
        #$SecurePassword = ConvertTo-SecureString $Pass -AsPlainText -Force
        #$cred = New-Object System.Management.Automation.PSCredential ($User, $SecurePassword)

        powershell.exe -ExecutionPolicy Bypass -File "C:\temp\UPTIME\EventLogCheck-1.ps1" `
        -ServerListPath "C:\Temp\UPTIME\ServerList.txt" `
        -Username $User `
        -Password $Pass
      register: script_output
      ignore_errors: yes

    - name: Display Script Output
      debug:
        var: script_output.stdout_lines
